### ISSUE TITLE
[BUG] Pixel 7 Pro seen as Pixel XL

### ISSUE THREAD

**Issue by warmoans** [Displax/safetynet-fix#10]
**Describe the bug & To reproduce**
Open Google One and phone is shown as Pixel XL. Ask a Google assistant device to find your phone and it says Pixel XL

**Expected behavior**
Phone should be seen as Pixel 7 Pro.

**Device info**
Device model: Pixel 7 Pro
Android version: 13
ROM name/version: June 2023

![Screenshot_20230624-091638](https://github.com/Displax/safetynet-fix/assets/37345461/12d4248e-4596-47d3-ab33-aefdcd918e32)
![Screenshot_20230624-091613](https://github.com/Displax/safetynet-fix/assets/37345461/38ee3a2d-294e-480a-99a1-bd3ca6782e9c)
![Screenshot_20230624-091557](https://github.com/Displax/safetynet-fix/assets/37345461/b0c2b9fa-858d-4741-abe2-74e228bbfd16)
EDIT: Removed log due to personal info on it.

Here are magisk modules I'm using. I don't think they would cause this.
![Screenshot_20230624-091842](https://github.com/Displax/safetynet-fix/assets/37345461/baba3719-7bd5-4b4b-ab87-6273f89d7c0e)

Let me know if you need anything else.

**Comment by warmoans** [comment]
You can rename devices using the Find Device app from Google. This fixed naming in Google One. I'm going to close bug report.

**Comment by VisionR1** [comment]
@Displax can you check this? Is not exaclty a bug, this phone Google Pixel XL (marlin) is use it to spoof for pass safetynet, but the strange is the programmer say this (This doesn't break other features because key attestation is only blocked for Play Services, and even within Play Services, it's only blocked for SafetyNet code. As a result, other attestation-based features (such as using the device as a security key) continue to work.) for that im little confused how your google one and Google assistant  in your phone read the fake device who is only for spoof in safetynet, my question is, so what other apps read the fake device? only google or and other etc. and can break features

**Comment by warmoans** [comment]
Try renaming device in Find My Network app/settings. Happened to me and all that changed was the device name.
