### ISSUE TITLE
Pixel 7 Pro - pass both basic integrity and CTS. After some seconds if i test it again i fail both.

### ISSUE THREAD

**Issue by SplyzerRB** [Displax/safetynet-fix#11]
**Describe the bug**
if i start the pixel 7 pro - i pass both basic integrity and CTS. After some seconds if i test it again i fail both.

**Screenshots of SafetyNet & Play Integrity API tests result**
![photo_2023-07-02_12-50-25](https://github.com/Displax/safetynet-fix/assets/89698413/0faf788a-ed57-4774-bb85-e14101f05a25)
![photo_2023-07-02_12-50-28](https://github.com/Displax/safetynet-fix/assets/89698413/6af04f95-46fc-4cf4-a1a6-b1dd77d44a9e)
![photo_2023-07-02_12-50-29](https://github.com/Displax/safetynet-fix/assets/89698413/ee68ff15-c408-4ea8-a1e0-8ce2b724bbdf)
![photo_2023-07-02_12-50-30](https://github.com/Displax/safetynet-fix/assets/89698413/be457eaa-7754-4de1-8ccf-faf975edf0f4)

**Device info**
Device model: Pixel 7 Pro
Android version: 13
ROM name/version: 13.0.0 (TQ2A.230505.002, Mai 2023)

**Comment by Displax** [comment]
Something in your ROM sets selinux to permissive. Do not do this.

**Comment by SplyzerRB** [comment]
@Displax i am on stock rom

**Comment by Jon8RFC** [comment]
I thought Magisk Hide Props Config was recommended as "do not use" over a year ago due to various issues it causes in making safetynet/integrity fail.

I'm on a Pixel 7 pro and I have no issues with safetynet-fix mod 1.3, and I haven't used props config in over two years, I think.

I used an lsposed module last month which caused things to fail, however.  If I were you, I would:

1. disable all modules in magisk except safetynet-fix mod 1.3
2. disable all lsposed modules
3. reboot
4. force close and clear data for both apps: "google play store" and "google play services" (select "show system" from the top-right menu in "all apps", or else it won't list)
5. reboot again.

Something new hasn't rolled out to play services, otherwise others would be mentioning it.  So if you're on a Pixel with stock rom, then it's highly likely to be caused by another module in magisk, a module in lsposed, or something else you've modified using the power of root.
